jobs:
  - job: Linux_GCC
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        sudo add-apt-repository -y ppa:neovim-ppa/stable
        sudo apt update -y
        sudo apt install -y libqt5svg5-dev neovim ninja-build qt5-default
      displayName: Install Dependencies
    - task: CMake@1
      inputs:
        workingDirectory: $(Build.BinariesDirectory)
        cmakeArgs: -GNinja -DCMAKE_BUILD_TYPE=Debug $(Build.SourcesDirectory)
      displayName: CMake Configure
    - task: CMake@1
      inputs:
        workingDirectory: $(Build.BinariesDirectory)
        cmakeArgs: --build .
      displayName: CMake Build


  - job: Linux_Clang_Clazy
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - script: |
        sudo add-apt-repository -y ppa:neovim-ppa/stable
        sudo apt update -y
        sudo apt install -y clazy libqt5svg5-dev neovim ninja-build qt5-default
      displayName: Install Dependencies
    - task: CMake@1
      inputs:
        workingDirectory: $(Build.BinariesDirectory)
        cmakeArgs: -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clazy -DENABLE_CLAZY=1 $(Build.SourcesDirectory)
      displayName: CMake Configure
    - task: CMake@1
      inputs:
        workingDirectory: $(Build.BinariesDirectory)
        cmakeArgs: --build .
      displayName: CMake Build


  - job: Apple
    pool:
      vmImage: 'macOS-latest'
    steps:
    - script: brew install msgpack neovim ninja qt5
      displayName: Install Dependencies
    - task: CMake@1
      inputs:
        workingDirectory: $(Build.BinariesDirectory)
        cmakeArgs: -GNinja -DUSE_SYSTEM_MSGPACK=OFF -DCMAKE_BUILD_TYPE=Debug $(Build.SourcesDirectory)
      displayName: CMake Configure
    - task: CMake@1
      inputs:
        workingDirectory: $(Build.BinariesDirectory)
        cmakeArgs: --build .
      displayName: CMake Build


  - job: Windows
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        architecture: 'x64'
      displayName: Setup Python
    - script: |
        cinst --no-progress -y 7zip neovim
        pip install aqtinstall
        cd $(Build.BinariesDirectory)
        python -m aqt install 5.15.0 windows desktop win64_msvc2019_64
      displayName: Install Dependencies
    - powershell: |
        Write-Host "##vso[task.setvariable variable=PATH;]${env:PATH};C:\tools\neovim\Neovim\bin";
      displayName: Add Neovim to PATH
    - task: CMake@1
      inputs:
        workingDirectory: $(Build.BinariesDirectory)
        cmakeArgs: -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=$(Build.BinariesDirectory)\5.15.0\msvc2019_64\lib\cmake;$(Build.BinariesDirectory)\5.15.0\msvc2019_64\bin $(Build.SourcesDirectory)
      displayName: CMake Configure
    - task: CMake@1
      inputs:
        workingDirectory: $(Build.BinariesDirectory)
        cmakeArgs: --build .
      displayName: CMake Build
