name: Build And Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BuildTest:
    name: Windows
    strategy:
      fail-fast: true
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build and Deploy
        env:
          CMAKE_BUILD_TYPE: Release
          CMAKE_GENERATOR: Ninja
        run: |
          iwr "https://github.com/neovim/neovim/releases/download/stable/nvim-win64.zip" -OutFile Neovim.zip
          7z x Neovim.zip
          $env:Path += ";" + $PWD.Path + "\nvim-win64\bin"
          nvim --version
          cmake -B ./build -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DENABLE_TESTS=ON
          cmake --build ${{ github.workspace }}/build --config Release --target install
          cd build
          cpack --verbose -G WIX
        # cd build
        # ctest -VV --timeout 120 --output-on-failure -C Release
        shell: pwsh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows_Release
          if-no-files-found: error
          path: |
            neovim-qt.zip
            build/neovim-qt-installer.msi

