name: Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Clazy:
    name: Clazy
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:neovim-ppa/unstable
          sudo apt-get install -y libqt5svg5-dev neovim ninja-build clazy qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
          sudo apt-get update -y
          mkdir build
          cd build

      - name: Configure
        run: >
          cmake -B ${{ github.workspace }}/build -GNinja -DCMAKE_BUILD_TYPE=Debug -DENABLE_CLAZY=1
          -DCMAKE_CXX_COMPILER=clazy

      - name: Build
        run: cmake --build ${{ github.workspace }}/build

  ClangTidy:
    name: ClangTidy
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:neovim-ppa/unstable
          sudo apt-get install -y clang-tidy-11 libqt5svg5-dev neovim ninja-build clazy qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
          sudo apt-get update -y
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/lib/llvm-11/bin/clang-tidy 100
          mkdir build

      - name: Configure
        run: |
          cmake -B ${{ github.workspace }}/build -GNinja -DCMAKE_BUILD_TYPE=Debug -DENABLE_TIDY=1

      - name: Build
        run: cmake --build ${{ github.workspace }}/build
