name: Bindings

on:
  pull_request:
    branches: [ master ]
    paths: [ 'bindings/*']

jobs:
  GenerateFromBinary:
    name: API_${{ matrix.version }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - version: 2
            nvim: 0.2.0
          - version: 3
            nvim: 0.2.2
          - version: 4
            nvim: 0.3.1
          - version: 5
            nvim: 0.3.8
          - version: 6
            nvim: 0.4.4
          - version: 7
            nvim: 0.5.0
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        env:
          URL: https://github.com/neovim/neovim/releases/download/v${{ matrix.nvim }}/nvim-win64.zip
        run: |
          New-Item -Path ${{ github.workspace }}\build -Name "build" -ItemType "directory"
          Invoke-WebRequest ${{ env.url }} -OutFile nvim-win64.zip
          Expand-Archive -Path nvim-win64.zip -DestinationPath ${{ github.workspace }}\build\

      - name: Install Dependencies
        run: |
          pip install jinja2 msgpack
          choco install dos2unix

      - name: Generate Bindings
        env:
          GEN_CMD: ${{ github.workspace }}\bindings\generate_bindings.py
          NVIM_EXE: ${{ github.workspace }}\build\Neovim\bin\nvim.exe
          OUTPUT: ${{ github.workspace }}\src\auto
        run: |
          ${{ env.nvim_exe }} --version
          python ${{ env.gen_cmd }} ${{ env.nvim_exe }} ${{ env.output }}
          dos2unix src/auto/neovimapi${{ matrix.version }}.cpp
          dos2unix src/auto/neovimapi${{ matrix.version }}.h

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Neovim API ${{ matrix.version}} Bindings
          path: |
            src/auto/neovimapi${{ matrix.version }}.cpp
            src/auto/neovimapi${{ matrix.version }}.h

      # This should run under mutex, however GitHub Actions does not appear to
      # have step mutex mechanism. Instead, using max-parallel: 1
      - name: Auto-Commit
        if: contains(github.event.pull_request.labels.*.name, 'auto-commit')
        run: |
          git add src/auto/neovimapi${{ matrix.version }}.cpp
          git add src/auto/neovimapi${{ matrix.version }}.h
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git commit -m "AUTO: Neovim API ${{ matrix.version }}"
          git push
